import fs from 'fs'

const traits = [
  {id:"syn_bastion",name:"Bastion",desc:"Bastion units gain bonus armor and magic resist. On dropping below 50% HP, they gain a shield.",ths:[{c:2,e:"+20 armor/mr, 15% HP shield below 50%"},{c:4,e:"+45 armor/mr, 25% HP shield below 50%"},{c:6,e:"+75 armor/mr, 40% HP shield below 50%, shield refreshes every 8s"}],best:["Aatrox","Poppy","Jax","Ornn","Rammus"],comps:["Bastion Vanguard","Bastion N.O.V.A."],counters:["Shred","Magic Pen"],type:"defense"},
  {id:"syn_nova",name:"N.O.V.A.",desc:"N.O.V.A. units deal bonus damage to low HP targets and gain range. Spells can critically strike.",ths:[{c:2,e:"+15% damage below 50% HP, +1 range"},{c:3,e:"+30% damage below 50% HP, +2 range, spells can crit at 100% crit damage"},{c:4,e:"+50% damage below 50% HP, +3 range, spell crit at 150% damage, execute below 10% HP"}],best:["Aatrox","Caitlyn","Akali","Maokai","Kindred"],comps:["N.O.V.A. Sniper","N.O.V.A. Eradicator"],counters:["Bruiser","Mecha"],type:"offense"},
  {id:"syn_rogue",name:"Rogue",desc:"Rogues leap to the backline at combat start. They gain bonus crit chance and crit damage.",ths:[{c:2,e:"Leap to backline, +15% crit chance"},{c:3,e:"Leap to backline, +30% crit chance, +20% crit damage"},{c:4,e:"Leap to backline, +45% crit chance, +40% crit damage, heal 15% on kill"}],best:["Briar","Talon","Gwen","Fizz","Kai'Sa","Riven"],comps:["Rogue Anima","Rogue Meeple"],counters:["Vanguard","Bastion"],type:"offense"},
  {id:"syn_primordian",name:"Primordian",desc:"Primordians are ancient beings. On kill, spawn swarmlings that fight for you. Swarmlings inherit stats.",ths:[{c:2,e:"15% chance to spawn swarmling on kill (20% stats, 6s)"},{c:3,e:"30% chance, 2 swarmlings max (30% stats, 8s)"},{c:4,e:"50% chance, 3 swarmlings max (40% stats, 10s), swarmlings explode on death"},{c:5,e:"75% chance, 4 swarmlings max (50% stats, 12s), explode + apply grievous wounds"}],best:["Briar","Rek'Sai","Bel'Veth"],comps:["Primordian Swarm","Primordian Mecha"],counters:["AOE","Shred"],type:"offense"},
  {id:"syn_anima",name:"Anima",desc:"Anima units are spirits of living worlds. They regenerate HP and their first cast is empowered. Grant omnivamp to adjacent allies.",ths:[{c:2,e:"3% max HP regen per 5s, first cast +25% effect"},{c:3,e:"5% max HP regen per 5s, first cast +50% effect, adjacent allies gain 8% omnivamp"},{c:4,e:"8% max HP regen per 5s, first cast +75% effect, adjacent allies gain 15% omnivamp, immune to first CC"}],best:["Briar","Jinx","Aurora","Illaoi","Kai'Sa","Fiora"],comps:["Anima Squad","Anima Force"],counters:["Grievous Wounds","Burst"],type:"hybrid"},
  {id:"syn_fateweaver",name:"Fateweaver",desc:"Fateweavers manipulate destiny. Each round, one Fateweaver gains a random powerful buff. More Fateweavers = stronger buffs.",ths:[{c:2,e:"1 random Fateweaver gains +30% AP/AD"},{c:3,e:"All Fateweavers gain +20% AP/AD and 20 mana on kill"},{c:4,e:"All Fateweavers gain +35% AP/AD, 30 mana on kill, and +1 item component on round win"}],best:["Caitlyn","Twisted Fate","Milio","Corki"],comps:["Fateweaver Sniper","Fateweaver Timebreaker"],counters:["Assassin","Silence"],type:"utility"},
  {id:"syn_sniper",name:"Sniper",desc:"Snipers deal bonus damage based on distance to target and have bonus range.",ths:[{c:2,e:"+1 range, +8% damage per hex of distance (max 40%)"},{c:4,e:"+2 range, +15% damage per hex of distance (max 75%), attacks cannot miss"}],best:["Ezreal","Gnar","Samira","Corki","Jhin","Xayah"],comps:["N.O.V.A. Sniper","Fateweaver Sniper"],counters:["Rogue","Assassin"],type:"offense"},
  {id:"syn_timebreaker",name:"Timebreaker",desc:"Timebreakers manipulate time. Their spells slow enemies and grant allies haste. Timebreaker casts rewind ally cooldowns.",ths:[{c:2,e:"Spells slow by 20% for 3s, allies gain 10% AS"},{c:3,e:"Spells slow by 35% for 4s, allies gain 20% AS, cleanse debuffs on cast"},{c:4,e:"Spells slow by 50% for 5s, allies gain 35% AS, cleanse + reduce cooldowns by 1s"}],best:["Ezreal","Milio","Pantheon","Riven"],comps:["Timebreaker Squad","Sniper Timebreaker"],counters:["Silence","CC"],type:"utility"},
  {id:"syn_brawler",name:"Brawler",desc:"Brawlers gain bonus HP and their attacks have a chance to stun. More Brawlers = more HP and stun chance.",ths:[{c:2,e:"+200 HP, 15% stun chance for 1s"},{c:4,e:"+500 HP, 25% stun chance for 1.5s"},{c:6,e:"+900 HP, 40% stun chance for 2s, stun chains to 1 nearby enemy"}],best:["Cho'Gath","Rek'Sai","Gragas","Illaoi","Maokai","Urgot"],comps:["Brawler Vanguard","Brawler Dark Star"],counters:["Shred","Magic Pen"],type:"defense"},
  {id:"syn_dark_star",name:"Dark Star",desc:"Dark Star units feed on death. When any unit dies, Dark Star units gain stacking AP/AD. Executes on low HP.",ths:[{c:2,e:"+8 AP/AD on any death, max 4 stacks"},{c:3,e:"+15 AP/AD on any death, max 6 stacks, execute below 15% HP"},{c:4,e:"+25 AP/AD on any death, max 8 stacks, execute below 20% HP, heal 10%"},{c:5,e:"+40 AP/AD on any death, max 10 stacks, execute below 25% HP, heal 20%"}],best:["Cho'Gath","Lissandra","Mordekaiser","Kai'Sa","Karma","Jhin"],comps:["Dark Star Reborn","Dark Star Psionic"],counters:["Divine","Arbiter"],type:"offense"},
  {id:"syn_vanguard",name:"Vanguard",desc:"Vanguards are elite defenders. They taunt nearby enemies and gain bonus damage reduction.",ths:[{c:2,e:"Taunt 1 nearest enemy for 2s, +10% DR"},{c:3,e:"Taunt 2 nearest enemies for 2.5s, +20% DR, +150 HP"},{c:4,e:"Taunt 3 nearest enemies for 3s, +30% DR, +400 HP, allies adjacent gain 5% DR"}],best:["Leona","Nasus","Mordekaiser","Illaoi","Nunu","Blitzcrank"],comps:["Vanguard Arbiter","Brawler Vanguard"],counters:["Shred","Magic Pen"],type:"defense"},
  {id:"syn_arbiter",name:"Arbiter",desc:"Arbiters judge the battlefield. Before combat, reveal enemy board layout. Deal bonus damage to highest HP enemy.",ths:[{c:2,e:"Reveal board, +10% damage to highest HP enemy"},{c:3,e:"Reveal + see items, +20% damage to highest HP"},{c:4,e:"Full reveal (items, traits, stars), +35% damage to highest HP"}],best:["Leona","Talon","Zoe","Diana","Leblanc"],comps:["Arbiter Court","Challenger Arbiter"],counters:["Divine","Mecha"],type:"utility"},
  {id:"syn_shepherd",name:"Shepherd",desc:"Shepherds guide and protect allies. They heal the lowest HP ally on cast and grant shields.",ths:[{c:2,e:"Heal lowest ally for 100 + 15% max HP on cast"},{c:3,e:"Heal lowest ally for 200 + 25% max HP + shield 150 HP"},{c:4,e:"Heal lowest ally for 350 + 35% max HP + shield 300 HP, cleanse grievous wounds"}],best:["Lissandra","Teemo","Meepsie","Illaoi","Lulu","Leblanc","Sona"],comps:["Shepherd Arbiter","Vanguard Shepherd"],counters:["Anti-heal","Burst"],type:"utility"},
  {id:"syn_replicator",name:"Replicator",desc:"Replicators create copies of themselves or allies at combat start. Clones have reduced stats but cast abilities.",ths:[{c:2,e:"Create 1 clone with 25% HP and no items. Clone dies in 6s"},{c:3,e:"Create 1 clone with 40% HP and 1 item. Clone dies in 8s"},{c:4,e:"Create 1 clone with 60% HP and all items. Clone dies in 10s, on death heals nearest ally for 20% max HP"}],best:["Lissandra","Veigar","Pantheon","Lulu","Nami"],comps:["Replicator Stargazer","Shepherd Replicator"],counters:["AOE","Execute"],type:"utility"},
  {id:"syn_space_groove",name:"Space Groove",desc:"Space Groove units channel cosmic rhythm. Each cast grants permanent stacking buffs to all allies (AP or AS). Persists between rounds.",ths:[{c:2,e:"+3 AP or AS per cast, stacks up to 10"},{c:3,e:"+5 AP or AS per cast, stacks up to 15, +10% cast speed"},{c:4,e:"+8 AP or AS per cast, stacks up to 20, +20% cast speed, overflow shields 200 HP"},{c:5,e:"+12 AP or AS per cast, infinite stacks, +30% cast speed, overflow 300 HP shields"}],best:["Nasus","Teemo","Gwen","Ornn","Samira","Blitzcrank"],comps:["Groove Gang","Space Groove Party"],counters:["Assassin","Burst"],type:"hybrid"},
  {id:"syn_meeple",name:"Meeple",desc:"Each Meeple unit grants stacking team AS. On death, chance to spawn a clone with reduced stats.",ths:[{c:2,e:"+10% team AS per Meeple"},{c:3,e:"+15% team AS, 20% clone (30% stats, 4s)"},{c:4,e:"+20% team AS, 35% clone (35% stats, 5s)"},{c:5,e:"+30% team AS, 50% clone (40% stats, 6s)"}],best:["Poppy","Veigar","Gnar","Meepsie","Fizz","Rammus","Corki","Bard"],comps:["Meeple Mayhem","Meeple Sniper"],counters:["AOE","Dark Star"],type:"offense"},
  {id:"syn_stargazer",name:"Stargazer",desc:"Stargazers read cosmic patterns. Abilities have enhanced range/effects and reveal invisible enemies. Spells cannot be dodged.",ths:[{c:2,e:"+1 range, reveal invisible units within 2 hexes"},{c:3,e:"+2 range, reveal within 4 hexes, spells cannot miss"},{c:4,e:"+3 range, reveal entire board, spells cannot miss, bonus 15% crit chance"}],best:["Talon","Twisted Fate","Jax","Lulu","Nunu","Xayah"],comps:["Stargazer Council","Fateweaver Stargazer"],counters:["Assassin","Burst"],type:"utility"},
  {id:"syn_marauder",name:"Marauder",desc:"Marauders thrive in prolonged fights. They gain omnivamp and bonus AD that scales with missing HP.",ths:[{c:2,e:"+10% omnivamp, +1% AD per 1% missing HP"},{c:3,e:"+20% omnivamp, +2% AD per 1% missing HP, heal 50 HP on attack"},{c:4,e:"+35% omnivamp, +3% AD per 1% missing HP, heal 100 HP on attack, cannot drop below 1 HP for 3s"}],best:["Akali","Bel'Veth","Urgot","Fiora","Master Yi"],comps:["Marauder N.O.V.A.","Challenger Marauder"],counters:["Anti-heal","Burst"],type:"offense"},
  {id:"syn_challenger",name:"Challenger",desc:"Challengers are duelists. They gain stacking attack speed on hit and bonus AD.",ths:[{c:2,e:"+15% AS on hit (stacks 5x), +5% AD"},{c:3,e:"+25% AS on hit (stacks 8x), +10% AD, +10% lifesteal at max stacks"},{c:4,e:"+40% AS on hit (stacks 10x), +20% AD, +20% lifesteal at max stacks, reset stacks on kill"}],best:["Bel'Veth","Jinx","Diana","Kindred","Fiora"],comps:["Challenger Arbiter","Challenger Anima"],counters:["CC","Frozen Heart"],type:"offense"},
  {id:"syn_psionic",name:"Psionic",desc:"Psionic units manipulate minds. Their spells have bonus effects and can chain or reset on kill. Gain mana faster.",ths:[{c:2,e:"+15% spell power, spells chain to 1 nearby enemy at 50% damage"},{c:3,e:"+30% spell power, chain to 2 enemies, 15% chance to reset spell on kill"},{c:4,e:"+50% spell power, chain to 3 enemies, 30% reset chance, spells ignore 20% MR"}],best:["Gragas","Pyke","Viktor","Master Yi","Sona"],comps:["Psionic Overload","Voyager Psionic"],counters:["MR stacking","Mystic"],type:"offense"},
  {id:"syn_voyager",name:"Voyager",desc:"Voyagers traverse space freely. They gain bonus movement speed and dodge chance. On dodge, they counter-attack.",ths:[{c:2,e:"+15% dodge chance, counter-attack for 50% AD on dodge"},{c:3,e:"+25% dodge chance, counter-attack for 100% AD on dodge, +1 hex dash on dodge"},{c:4,e:"+40% dodge chance, counter-attack for 150% AD on dodge, dash + cleanse on dodge"}],best:["Meepsie","Pyke","Aurora","Karma","The Mighty Mech"],comps:["Voyager Anima","Voyager Mecha"],counters:["Cannot Miss","Stargazer"],type:"hybrid"},
  {id:"syn_channeler",name:"Channeler",desc:"Channelers accumulate cosmic energy. Each cast grants bonus AP to all allies. On reaching max stacks, release a shockwave.",ths:[{c:2,e:"+5 AP per cast (stacks 10x), shockwave at max for 150 AP damage"},{c:3,e:"+8 AP per cast (stacks 15x), shockwave at max for 300 AP damage + stun"},{c:4,e:"+12 AP per cast (stacks 20x), shockwave at max for 500 AP damage + stun + shield allies 200 HP"}],best:["Mordekaiser","Zoe","Aurelion Sol","Viktor","Bard","Karma"],comps:["Channeler Mecha","Channeler Arbiter"],counters:["Silence","CC"],type:"offense"},
  {id:"syn_mecha",name:"Mecha",desc:"Mecha units are armored constructs with bonus HP and damage reduction. At high Mecha count, all units gain a second passive.",ths:[{c:2,e:"+250 HP, +5% DR"},{c:3,e:"+600 HP, +10% DR"},{c:4,e:"+1100 HP, +15% DR, second passive"},{c:5,e:"+1800 HP, +20% DR, second passive, heal 5% on hit"}],best:["Urgot","Aurelion Sol","The Mighty Mech"],comps:["Mecha Frontline","Voyager Mecha"],counters:["Shred","Psionic"],type:"defense"},
  {id:"syn_party_animal",name:"Party Animal",desc:"Party Animals bring the celebration. Having a Party Animal grants all allies bonus loot and stats. Unique trait.",ths:[{c:1,e:"All allies gain +10% HP, +10% AP/AD. Shop refreshes cost 1 less gold every 4 rounds."}],best:["Blitzcrank"],comps:["Space Groove Party","Party Animal Vanguard"],counters:["None","Enjoy the party"],type:"utility"},
  {id:"syn_divine_duelist",name:"Divine Duelist",desc:"Divine Duelists are blessed warriors. They gain bonus stats and their attacks grant allies temporary shields. Unique trait.",ths:[{c:1,e:"Fiora gains +30% AS, +20% lifesteal, and grants 100 HP shield to 2 nearest allies on attack."}],best:["Fiora"],comps:["Divine Duelist Marauder","Anima Squad"],counters:["Anti-heal","CC"],type:"hybrid"},
  {id:"syn_eradicator",name:"Eradicator",desc:"Eradicators deal devastating damage to isolated targets. Their attacks ignore armor and MR on targets with no adjacent allies. Unique trait.",ths:[{c:1,e:"Jhin's attacks ignore 30% armor/MR on isolated targets. Every 4th attack deals +100% damage."}],best:["Jhin"],comps:["N.O.V.A. Eradicator","Eradicator Sniper"],counters:["Cluster","Vanguard"],type:"offense"},
  {id:"syn_commander",name:"Commander",desc:"Commanders lead from the backline. They grant powerful team-wide buffs that scale with star level. Unique trait.",ths:[{c:1,e:"All allies gain +20% AS and +15% AP/AD. On Sona's cast, all allies gain 30 mana."}],best:["Sona"],comps:["Commander Shepherd","Psionic Overload"],counters:["Assassin","Silence"],type:"utility"},
]

let out = `// TFT Synergies data -- Set 17: Space Gods (April 2026)\nexport interface Synergy {\n  id: string; name: string; description: string;\n  thresholds: Array<{ count: number; effect: string }>;\n  bestUnits: string[]; bestComps: string[]; counters: string[];\n  type: 'offense' | 'defense' | 'utility' | 'hybrid';\n}\n\nexport const SYNERGIES: Synergy[] = [\n`

for (const t of traits) {
  const ths = t.ths.map(x => `{count:${x.c},effect:${JSON.stringify(x.e)}}`).join(',')
  out += `  { id:${JSON.stringify(t.id)},name:${JSON.stringify(t.name)},description:${JSON.stringify(t.desc)},thresholds:[${ths}],bestUnits:${JSON.stringify(t.best)},bestComps:${JSON.stringify(t.comps)},counters:${JSON.stringify(t.counters)},type:${JSON.stringify(t.type)} },\n`
}

out += `]\n`
fs.writeFileSync('src/data/synergies.ts', out)
console.log('wrote synergies.ts')
