/** Types for `data/tft-static/en/*.json` (generated by scripts/parse-tft-static-data.mjs). */

export interface TFTStaticMeta {
  setNumber: number
  setPrefix: string
  setCoreName: string
  locale: string
  generatedAt: string
  sourceUrl: string
  counts: {
    units: number
    traits: number
    items: {
      components: number
      finished: number
      radiants: number
      artifacts: number
    }
    augments: number
    godBoons: number
  }
}

export interface TFTStaticIconFields {
  iconPath: string | null
  iconUrl: string | null
}

export interface TFTAbilityVariable {
  name: string
  value: number | number[]
}

export interface TFTStaticUnitAbility {
  name: string | null
  /** Raw CD text with @tokens@ (formatted at read time when variables present). */
  description: string
  variables?: TFTAbilityVariable[]
  iconPath: string | null
  iconUrl: string | null
}

export interface TFTStaticUnitStats {
  armor: number
  attackSpeed: number
  critChance: number
  critMultiplier: number
  damage: number
  hp: number
  initialMana: number
  magicResist: number
  mana: number
  range: number
}

export interface TFTStaticUnit extends TFTStaticIconFields {
  apiName: string
  name: string
  description: string
  cost: number | null
  traits: string[]
  ability: TFTStaticUnitAbility | null
  stats: TFTStaticUnitStats | null
  role: string | null
}

export interface TFTStaticTraitThreshold {
  minUnits: number
  maxUnits: number | null
  style: number | null
  variables: Record<string, number>
}

export interface TFTStaticTrait extends TFTStaticIconFields {
  apiName: string
  name: string
  description: string
  thresholds: TFTStaticTraitThreshold[]
}

export type TFTItemCategory = 'component' | 'finished' | 'radiant' | 'artifact'

export interface TFTStaticItem extends TFTStaticIconFields {
  apiName: string
  name: string
  description: string
  effects?: Record<string, number | undefined>
  composition: string[]
  from: string[] | null
  tags: string[]
  unique: boolean
  associatedTraits: string[]
  category: TFTItemCategory
}

export type TFTAugmentTier = 'silver' | 'gold' | 'prismatic' | 'unknown'

export interface TFTStaticAugment extends TFTStaticIconFields {
  apiName: string
  name: string
  /** Stripped description (legacy); prefer rawDescription + formatTftText at read time */
  description: string
  /** Raw TFT string with @placeholders@ preserved */
  rawDescription?: string
  tier: TFTAugmentTier
  associatedTraits: string[]
  effects: Record<string, number>
}

export interface TFTStaticGodBoon extends TFTStaticIconFields {
  apiName: string
  name: string
  description: string
  tier: TFTAugmentTier
  godKey: string
  godName: string
  isPrimary: boolean
  associatedTraits: string[]
  effects: Record<string, number>
}

export interface TFTDataCatalog {
  meta: TFTStaticMeta
  units: TFTStaticUnit[]
  traits: TFTStaticTrait[]
  items: TFTStaticItem[]
  itemsByCategory: Record<TFTItemCategory, TFTStaticItem[]>
  augments: TFTStaticAugment[]
  godBoons: TFTStaticGodBoon[]
  getUnitByApiName: (apiName: string) => TFTStaticUnit | undefined
  getTraitByApiName: (apiName: string) => TFTStaticTrait | undefined
  getItemByIdOrApiName: (identifier: string | number) => TFTStaticItem | undefined
  getAugmentByApiName: (apiName: string) => TFTStaticAugment | undefined
  getGodBoonByApiName: (apiName: string) => TFTStaticGodBoon | undefined
}
