/* eslint-disable */
// AUTO-GENERATED by scripts/generate-tft-from-riot.mjs — do not edit by hand.
// Source: Community Dragon → Riot TFT game data (tftchampions.json, tfttraits.json). Not League of Legends Summoner's Rift data.

export const TFT17_UNIT_TRAITS: Record<string, string[]> = {
  "Aatrox": [
    "N.O.V.A.",
    "Bastion"
  ],
  "Briar": [
    "Anima",
    "Primordian",
    "Rogue"
  ],
  "Caitlyn": [
    "N.O.V.A.",
    "Fateweaver"
  ],
  "Cho'Gath": [
    "Dark Star",
    "Brawler"
  ],
  "Ezreal": [
    "Timebreaker",
    "Sniper"
  ],
  "Leona": [
    "Arbiter",
    "Vanguard"
  ],
  "Lissandra": [
    "Dark Star",
    "Shepherd",
    "Replicator"
  ],
  "Nasus": [
    "Space Groove",
    "Vanguard"
  ],
  "Poppy": [
    "Meeple",
    "Bastion"
  ],
  "Rek'Sai": [
    "Primordian",
    "Brawler"
  ],
  "Talon": [
    "Stargazer",
    "Rogue"
  ],
  "Teemo": [
    "Space Groove",
    "Shepherd"
  ],
  "Twisted Fate": [
    "Stargazer",
    "Fateweaver"
  ],
  "Veigar": [
    "Meeple",
    "Replicator"
  ],
  "Akali": [
    "N.O.V.A.",
    "Marauder"
  ],
  "Bel'Veth": [
    "Primordian",
    "Challenger",
    "Marauder"
  ],
  "Gnar": [
    "Meeple",
    "Sniper"
  ],
  "Gragas": [
    "Psionic",
    "Brawler"
  ],
  "Gwen": [
    "Space Groove",
    "Rogue"
  ],
  "Jax": [
    "Stargazer",
    "Bastion"
  ],
  "Jinx": [
    "Anima",
    "Challenger"
  ],
  "Meepsie": [
    "Meeple",
    "Shepherd",
    "Voyager"
  ],
  "Milio": [
    "Timebreaker",
    "Fateweaver"
  ],
  "Mordekaiser": [
    "Dark Star",
    "Conduit",
    "Vanguard"
  ],
  "Pantheon": [
    "Timebreaker",
    "Brawler",
    "Replicator"
  ],
  "Pyke": [
    "Psionic",
    "Voyager"
  ],
  "Zoe": [
    "Arbiter",
    "Conduit"
  ],
  "Aurora": [
    "Anima",
    "Voyager"
  ],
  "Diana": [
    "Arbiter",
    "Challenger"
  ],
  "Fizz": [
    "Meeple",
    "Rogue"
  ],
  "Illaoi": [
    "Anima",
    "Vanguard",
    "Shepherd"
  ],
  "Kai'Sa": [
    "Dark Star",
    "Rogue"
  ],
  "Lulu": [
    "Stargazer",
    "Replicator"
  ],
  "Maokai": [
    "N.O.V.A.",
    "Brawler"
  ],
  "Ornn": [
    "Space Groove",
    "Bastion"
  ],
  "Samira": [
    "Space Groove",
    "Sniper"
  ],
  "Urgot": [
    "Mecha",
    "Brawler",
    "Marauder"
  ],
  "Viktor": [
    "Psionic",
    "Conduit"
  ],
  "Aurelion Sol": [
    "Mecha",
    "Conduit"
  ],
  "Corki": [
    "Meeple",
    "Fateweaver"
  ],
  "Karma": [
    "Dark Star",
    "Voyager"
  ],
  "Kindred": [
    "N.O.V.A.",
    "Challenger"
  ],
  "Leblanc": [
    "Arbiter",
    "Shepherd"
  ],
  "Master Yi": [
    "Psionic",
    "Marauder"
  ],
  "Nami": [
    "Space Groove",
    "Replicator"
  ],
  "Nunu": [
    "Stargazer",
    "Vanguard"
  ],
  "Rammus": [
    "Meeple",
    "Bastion"
  ],
  "Riven": [
    "Timebreaker",
    "Rogue"
  ],
  "The Mighty Mech": [
    "Mecha",
    "Voyager"
  ],
  "Xayah": [
    "Stargazer",
    "Sniper"
  ],
  "Bard": [
    "Meeple",
    "Conduit"
  ],
  "Blitzcrank": [
    "Party Animal",
    "Space Groove",
    "Vanguard"
  ],
  "Fiora": [
    "Divine Duelist",
    "Anima",
    "Marauder"
  ],
  "Jhin": [
    "Dark Star",
    "Eradicator",
    "Sniper"
  ],
  "Sona": [
    "Commander",
    "Psionic",
    "Shepherd"
  ]
}

export const SYNERGIES_FROM_RIOT_DATA = [
  {
    "id": "syn_anima",
    "name": "Anima",
    "description": "After losing a player combat, gain Tech, plus additional Tech equal to times the length of your loss streak. Additionally, gain Tech per Anima takedown.\n\nEach time Animas get Tech, they prototype new Anima Weapons. You can take them, or save your Tech to get more powerful weapons next time.\n\n Start Researching! \n\n After winning a player combat, gain loot!",
    "thresholds": [
      {
        "count": 3,
        "effect": "Tier bonus (see trait description)"
      },
      {
        "count": 6,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [
      "Aurora",
      "Briar",
      "Fiora",
      "Illaoi",
      "Jinx"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_arbiter",
    "name": "Arbiter",
    "description": "Scribe a unique divine law, allowing you to choose an effect to apply to Arbiters when a chosen cause occurs.\n\n Choose a cause and effect for your law\n\n Effects are stronger.",
    "thresholds": [
      {
        "count": 2,
        "effect": "OutputMultiplier: 1"
      },
      {
        "count": 3,
        "effect": "OutputMultiplier: 1"
      }
    ],
    "bestUnits": [
      "Diana",
      "Leblanc",
      "Leona",
      "Zoe"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_bastion",
    "name": "Bastion",
    "description": "Your team gains Armor and Magic Resist.\n\nBastions gain more, and the value doubles in the first seconds of combat.\n\n \n\n \n\n ; Non-Bastions gain an additional .",
    "thresholds": [
      {
        "count": 2,
        "effect": "BonusArmor: 16 · BonusMR: 16 · Duration: 10 · StatMultiplier: 2 · TeamwideResists: 15"
      },
      {
        "count": 4,
        "effect": "BonusArmor: 40 · BonusMR: 40 · Duration: 10 · StatMultiplier: 2 · TeamwideResists: 15"
      },
      {
        "count": 6,
        "effect": "BonusArmor: 60 · BonusMR: 60 · Duration: 10 · StatMultiplier: 2 · TeamwideResists: 15"
      }
    ],
    "bestUnits": [
      "Aatrox",
      "Jax",
      "Ornn",
      "Poppy",
      "Rammus"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_brawler",
    "name": "Brawler",
    "description": "Your team gains Health. Brawlers gain more.",
    "thresholds": [
      {
        "count": 2,
        "effect": "HealthBonus: 25%"
      },
      {
        "count": 4,
        "effect": "HealthBonus: 45%"
      },
      {
        "count": 6,
        "effect": "HealthBonus: 65%"
      }
    ],
    "bestUnits": [
      "Cho'Gath",
      "Gragas",
      "Maokai",
      "Pantheon",
      "Rek'Sai",
      "Urgot"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_bulwark",
    "name": "Bulwark",
    "description": "Summon a placeable relic. At the start of combat, it grants adjacent allies a max Health shield and Attack Speed.",
    "thresholds": [
      {
        "count": 1,
        "effect": "AttackSpeed: 10% · AttackSpeedDuration: 60 · PercentHealthShield: 10% · ShieldDuration: 60"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_challenger",
    "name": "Challenger",
    "description": "Your team gains Attack Speed. Challengers gain bonus Attack Speed. When their target dies, Challengers dash to a new target and increase their Attack Speed bonus by for seconds.",
    "thresholds": [
      {
        "count": 2,
        "effect": "AttackSpeedPercent: 15% · DamageReduction: 0"
      },
      {
        "count": 3,
        "effect": "AttackSpeedPercent: 22% · DamageReduction: 0"
      },
      {
        "count": 4,
        "effect": "AttackSpeedPercent: 40% · DamageReduction: 0"
      },
      {
        "count": 5,
        "effect": "AttackSpeedPercent: 55% · DamageReduction: 0"
      }
    ],
    "bestUnits": [
      "Bel'Veth",
      "Diana",
      "Jinx",
      "Kindred"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_choose_trait",
    "name": "Choose Trait",
    "description": "When you field Miss Fortune, choose between Conduit Mode, Challenger Mode, and Replicator Mode. Miss Fortune has a unique ability based on her mode and gains the associated trait.",
    "thresholds": [],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_commander",
    "name": "Commander",
    "description": "Sona gives you a random Command Mod every rounds which allows you to alter the way an ally behaves during combat. Command Mods last player combats even if they are not equipped.",
    "thresholds": [
      {
        "count": 1,
        "effect": "AS: 15% · HealthRatio: 15% · RoundsPerMod: 2"
      }
    ],
    "bestUnits": [
      "Sona"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_conduit",
    "name": "Conduit",
    "description": "Innate: Conduits gain additional Mana from all sources.\n\nYour team gains Mana Regen, increased for Conduits.",
    "thresholds": [
      {
        "count": 2,
        "effect": "ConduitManaRegen: 3 · TeamManaRegen: 1"
      },
      {
        "count": 3,
        "effect": "ConduitManaRegen: 5 · TeamManaRegen: 1"
      },
      {
        "count": 4,
        "effect": "ConduitManaRegen: 7 · TeamManaRegen: 2"
      },
      {
        "count": 5,
        "effect": "ConduitManaRegen: 9 · TeamManaRegen: 3"
      }
    ],
    "bestUnits": [
      "Aurelion Sol",
      "Bard",
      "Mordekaiser",
      "Viktor",
      "Zoe"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_dark_lady",
    "name": "Dark Lady",
    "description": "Allies take less damage from abilities, increased to while Morgana is in Dark Form.",
    "thresholds": [
      {
        "count": 1,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_dark_star",
    "name": "Dark Star",
    "description": "Dark Stars create a black hole that consumes enemies at max health.\n\n AND they gain .\n\n AND the strongest Dark Star unit goes supermassive, gaining effectiveness from Dark Star, and creates 2 minor Black Holes.\n\n All Dark Stars are supermassive. At level 10, CONSUME EVERYONE.",
    "thresholds": [
      {
        "count": 2,
        "effect": "Tier bonus (see trait description)"
      },
      {
        "count": 4,
        "effect": "Tier bonus (see trait description)"
      },
      {
        "count": 6,
        "effect": "Tier bonus (see trait description)"
      },
      {
        "count": 9,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [
      "Cho'Gath",
      "Jhin",
      "Kai'Sa",
      "Karma",
      "Lissandra",
      "Mordekaiser"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_divine_duelist",
    "name": "Divine Duelist",
    "description": "Your Tactician heals for of player damage dealt from winning.\n\nFiora always wins a one on one duel.",
    "thresholds": [
      {
        "count": 1,
        "effect": "DUHeal: 1 · PVEHP: 1 · PVENumWins: 4 · PlayerOmnivamp: 15%"
      }
    ],
    "bestUnits": [
      "Fiora"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_doomer",
    "name": "Doomer",
    "description": "Combat Start: Mark all enemies with Doom.\n\nThe first time enemies are damaged each combat, their Doom is consumed, stealing Attack Damage and Ability Power from them and granting it to your strongest Vex.",
    "thresholds": [
      {
        "count": 1,
        "effect": "ADAP1: 12"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_eradicator",
    "name": "Eradicator",
    "description": "Enemies have less Armor and Magic Resist.",
    "thresholds": [
      {
        "count": 1,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [
      "Jhin"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_factory_new",
    "name": "Factory New",
    "description": "After participating in combat, open an armory to purchase a permanent upgrade for your strongest Graves.\n\nEvery upgrades, future upgrades will take an additional round.\n\nNext Upgrade: Rounds.",
    "thresholds": [
      {
        "count": 1,
        "effect": "NumberOfUpgradesBeforeRoundCostIncrease: 3"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_fateweaver",
    "name": "Fateweaver",
    "description": "Innate: Fateweavers have Precision.\n\n Chance effects on abilities are Lucky.\n\n Gain Crit Chance and Crit Damage. Critical strikes are also Lucky.\n\nPrecision: Ability damage can critically strike. Additional Precision grants 10 Critical Strike Damage.\nLucky: Check twice and take the better outcome.",
    "thresholds": [
      {
        "count": 2,
        "effect": "CritDamage: 0"
      },
      {
        "count": 4,
        "effect": "CritChance: 20% · CritDamage: 20"
      }
    ],
    "bestUnits": [
      "Caitlyn",
      "Corki",
      "Milio",
      "Twisted Fate"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_galaxy_hunter",
    "name": "Galaxy Hunter",
    "description": "Zed is obtained from the Invader Zed augment.\n\nWhile at least one clone is alive, Zed gains bonus Attack Damage.",
    "thresholds": [
      {
        "count": 1,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_gun_goddess",
    "name": "Gun Goddess",
    "description": "When you field Miss Fortune, choose between Conduit Mode, Challenger Mode, and Replicator Mode. Miss Fortune has a unique ability based on her mode and gains the associated trait.",
    "thresholds": [
      {
        "count": 1,
        "effect": "Allies: 2 · DamageAmp: 1% · FlatDamage: 100 · Mana: 2 · NumAttacks: 3"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_marauder",
    "name": "Marauder",
    "description": "Your team gains Omnivamp. Marauders gain more Omnivamp, Attack Damage, and their Omnivamp overhealing is converted into Shield (up to max Health.) , , , .",
    "thresholds": [
      {
        "count": 2,
        "effect": "AD: 20% · Omnivamp: 5% · ShieldAD: 0"
      },
      {
        "count": 4,
        "effect": "AD: 40% · Omnivamp: 7% · ShieldAD: 0"
      },
      {
        "count": 6,
        "effect": "AD: 60% · Omnivamp: 10% · ShieldAD: 20%"
      }
    ],
    "bestUnits": [
      "Akali",
      "Bel'Veth",
      "Fiora",
      "Master Yi",
      "Urgot"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_mecha",
    "name": "Mecha",
    "description": "Innate: Mecha units can transform into their Ultimate form, upgrading their ability and gaining Health. Transformed Mechas take up two team slots and count twice for the Mecha trait.\n\n Energy Cells: Mechas gain .\n\n Overclocked Cells: Increased to .\n\n Precision Engineering: + max team size\n\nUse the Mecha-Former item to toggle the forms of your Mecha units",
    "thresholds": [
      {
        "count": 3,
        "effect": "AD: 25% · AP: 25"
      },
      {
        "count": 4,
        "effect": "AD: 45% · AP: 45"
      },
      {
        "count": 6,
        "effect": "AD: 35% · AP: 35"
      }
    ],
    "bestUnits": [
      "Aurelion Sol",
      "The Mighty Mech",
      "Urgot"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_meeple",
    "name": "Meeple",
    "description": "Meeple attract Meeps that empower Meeple abilities in meepy ways. They also gain bonus Health.\n\n , \n\n , \n\n , . Create a Cloning Slot on your bench. Gain gold and a 1-star copy of the champion placed there when cloning completes.\n\n , . SUMMON THE FOUR MEEPLORDS!\n\nCloning time = Champion cost",
    "thresholds": [
      {
        "count": 3,
        "effect": "BonusHealth: 100 · Meeps: 2"
      },
      {
        "count": 5,
        "effect": "BonusHealth: 400 · Meeps: 3"
      },
      {
        "count": 7,
        "effect": "BonusHealth: 400 · Meeps: 4"
      },
      {
        "count": 10,
        "effect": "BonusHealth: 500 · Meeps: 6"
      }
    ],
    "bestUnits": [
      "Bard",
      "Corki",
      "Fizz",
      "Gnar",
      "Meepsie",
      "Poppy",
      "Rammus",
      "Veigar"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_n_o_v_a",
    "name": "N.O.V.A.",
    "description": "seconds into combat, N.O.V.A. grant a power surge to allies based on champions.\n\n Gain a Striker selector. The chosen N.O.V.A. activates their Strike during the power surge.\n\nAatrox: Ally Damage Shred and Sunders enemiesAatrox: Shred and Sunder enemies\nCaitlyn: Grant allies Attack SpeedCaitlyn: Grant Attack Speed\nAkali: Allies gain PrecisionAkali: Allies gain Precision\nMaokai: Allies heal max HealthMaokai: Heal allies\nKindred: Shield the strongest Tank for Kindred: Shield an ally\nEmblem: Allies deal stacking bonus true damageEmblem: Deal bonus true damage",
    "thresholds": [
      {
        "count": 2,
        "effect": "Tier bonus (see trait description)"
      },
      {
        "count": 5,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [
      "Aatrox",
      "Akali",
      "Caitlyn",
      "Kindred",
      "Maokai"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_oracle",
    "name": "Oracle",
    "description": "Every rounds, Tahm Kench grants a reward!\n\nRounds Remaining: \nLast Reward:",
    "thresholds": [
      {
        "count": 1,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_party_animal",
    "name": "Party Animal",
    "description": "Once per combat, after falling below percent Health, become untargetable and repair max Health per second. Upon reaching full Health, or when no other allies remain, return to combat. If fully healed, for the rest of combat Blitzcrank is in The Groove and Party Crasher's passive fires bolts four times as fast.",
    "thresholds": [
      {
        "count": 1,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [
      "Blitzcrank"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_primordian",
    "name": "Primordian",
    "description": "Dealing damage spawns Swarmlings based on unique Primordian star level.\n\n Spawn more Swarmlings! After each player combat, gain a random 1 or 2-cost champion. of damage taken contributes to damage dealt.",
    "thresholds": [
      {
        "count": 2,
        "effect": "DamageMultiplier: 1"
      },
      {
        "count": 3,
        "effect": "DamageMultiplier: 1.45"
      }
    ],
    "bestUnits": [
      "Bel'Veth",
      "Briar",
      "Rek'Sai"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_psionic",
    "name": "Psionic",
    "description": "Gain Psionic items that can be equipped to any ally.\n\n Gain the \n\n Gain the , Psionic items gain extra effects on Psionic units",
    "thresholds": [
      {
        "count": 2,
        "effect": "TooltipOnlyEffectiveness: 0"
      },
      {
        "count": 4,
        "effect": "TooltipOnlyEffectiveness: 50"
      }
    ],
    "bestUnits": [
      "Gragas",
      "Master Yi",
      "Pyke",
      "Sona",
      "Viktor"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_redeemer",
    "name": "Redeemer",
    "description": "For each non-unique trait you have active, your team gains /%/ Attack Speed, and // Armor and Magic Resist.\n\nTeamwide Attack Speed: Teamwide Resists:",
    "thresholds": [
      {
        "count": 1,
        "effect": "BonusDefensiveStat1: 2 · BonusDefensiveStat2: 2.5 · BonusDefensiveStat3: 3 · BonusOffensiveStat1: 2% · BonusOffensiveStat2: 3% · BonusOffensiveStat3: 3%"
      }
    ],
    "bestUnits": [],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_replicator",
    "name": "Replicator",
    "description": "Replicator abilities occur a second time at reduced effectiveness.",
    "thresholds": [
      {
        "count": 2,
        "effect": "Effectiveness: 22%"
      },
      {
        "count": 4,
        "effect": "Effectiveness: 45%"
      }
    ],
    "bestUnits": [
      "Lissandra",
      "Lulu",
      "Nami",
      "Pantheon",
      "Veigar"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_rogue",
    "name": "Rogue",
    "description": "Rogues gain Attack Damage and Ability Power. The first time they fall below health, they slip into shadows. Enemies targeting them are redirected to a nearby unit, preferring Tanks.",
    "thresholds": [
      {
        "count": 2,
        "effect": "AD: 12% · AP: 12 · Duration: 3"
      },
      {
        "count": 3,
        "effect": "AD: 25% · AP: 25 · Duration: 3"
      },
      {
        "count": 4,
        "effect": "AD: 40% · AP: 40 · Duration: 3"
      },
      {
        "count": 5,
        "effect": "AD: 55% · AP: 55 · Duration: 3"
      }
    ],
    "bestUnits": [
      "Briar",
      "Fizz",
      "Gwen",
      "Kai'Sa",
      "Riven",
      "Talon"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_shepherd",
    "name": "Shepherd",
    "description": "Shepherds summon the Bond of the Stars to aid them in battle.\n\n Summon Bia\n\n Summon Bayin\n\n Bia and Bayin's bond grows deeper\n\nBia and Bayin's power are increased by the total star level of all Shepherds.",
    "thresholds": [
      {
        "count": 3,
        "effect": "Tier bonus (see trait description)"
      },
      {
        "count": 5,
        "effect": "Tier bonus (see trait description)"
      },
      {
        "count": 7,
        "effect": "Tier bonus (see trait description)"
      }
    ],
    "bestUnits": [
      "Illaoi",
      "Leblanc",
      "Lissandra",
      "Meepsie",
      "Sona",
      "Teemo"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_sniper",
    "name": "Sniper",
    "description": "Snipers gain Damage Amp, increased against targets farther away. ; + per hex ; + per hex ; + per hex",
    "thresholds": [
      {
        "count": 2,
        "effect": "PerHexIncrease: 2 · PercentDamageIncrease: 18"
      },
      {
        "count": 3,
        "effect": "PerHexIncrease: 3 · PercentDamageIncrease: 24"
      },
      {
        "count": 4,
        "effect": "PerHexIncrease: 4 · PercentDamageIncrease: 28"
      }
    ],
    "bestUnits": [
      "Ezreal",
      "Gnar",
      "Jhin",
      "Samira",
      "Xayah"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_space_groove",
    "name": "Space Groove",
    "description": "Groovians can enter The Groove. While in it, they gain Attack Speed and max Health Regen, increased per Groovian on your team.\n\n All Groovians start combat in The Groove for seconds.\n\n Each second spent in The Groove grants stacking Attack Damage and Ability Power.\n\n Increase these effects by !\n\n Get your Groove on!\n\nThe Groove: @TFTUnitProperty.:TFT17_SpaceGroove_AS*100@ , @TFTUnitProperty.:TFT17_SpaceGroove_HealthRegen*100@",
    "thresholds": [
      {
        "count": 1,
        "effect": "ADAPPerSecond: 0 · EffectBonus: 0 · StartOfCombatDuration: 0"
      },
      {
        "count": 3,
        "effect": "ADAPPerSecond: 0 · EffectBonus: 0 · StartOfCombatDuration: 3"
      },
      {
        "count": 5,
        "effect": "ADAPPerSecond: 5 · EffectBonus: 0 · StartOfCombatDuration: 3"
      },
      {
        "count": 7,
        "effect": "ADAPPerSecond: 5 · EffectBonus: 10 · StartOfCombatDuration: 3"
      },
      {
        "count": 10,
        "effect": "ADAPPerSecond: 10 · EffectBonus: 500 · PrismaticDamage: 800 · PrismaticJumpDamage: 1500 · StartOfCombatDuration: 60"
      }
    ],
    "bestUnits": [
      "Blitzcrank",
      "Gwen",
      "Nami",
      "Nasus",
      "Ornn",
      "Samira",
      "Teemo"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_stargazer",
    "name": "Stargazer",
    "description": "Stargazers chart a different constellation every game.\n\nStargazers in empowered hexes gain various bonuses, starting at units.\n\nMore hexes reveal at each player level.",
    "thresholds": [
      {
        "count": 3,
        "effect": "Family_HexesToReveal_TOOLTIPONLY: 3 · Family_Stats: 10 · Fountain_HealPercent: 18% · Fountain_ManaRegen: 3 · Huntress_AS: 30% · Huntress_Heal: 5% · Medallion_DA: 20% · Medallion_Resists: 20 · Mountain_APPerHealthThreshold: 1 · Mountain_Health: 20% · NumMarks: 3 · Serpent_DR: 15% · Serpent_Poison: 30% · Shield_ADAP: 2% · Shield_CashoutAS: 18 · Shield_CashoutHP: 20 · Shield_Shield: 15% · Wolf_ADAP: 10 · Wolf_CriticalStrikeChance: 25% · Wolf_Gold: 1 · Wolf_Health: 2% · Wolf_ModifiedCriticalStrikeDamage: 1.3"
      },
      {
        "count": 5,
        "effect": "Family_HexesToReveal_TOOLTIPONLY: 2 · Family_Stats: 35 · Fountain_HealPercent: 25% · Fountain_ManaRegen: 4 · Huntress_AS: 45% · Huntress_Heal: 8% · Medallion_DA: 30% · Medallion_Resists: 30 · Mountain_ADAP: 12% · Mountain_APPerHealthThreshold: 2 · Mountain_Health: 30% · NumMarks: 5 · Serpent_DR: 20% · Serpent_Poison: 45% · Shield_ADAP: 3% · Shield_Shield: 25% · Wolf_ADAP: 15 · Wolf_CriticalStrikeChance: 35% · Wolf_Gold: 2 · Wolf_Health: 8% · Wolf_ModifiedCriticalStrikeDamage: 1.5"
      },
      {
        "count": 7,
        "effect": "Family_EmpoweredSharePercent: 30% · Family_Stats: 35 · Fountain_HealPercent: 20% · Fountain_ManaRegen: 5 · Huntress_AS: 60% · Huntress_Heal: 10% · Medallion_DA: 40% · Medallion_Resists: 40 · Mountain_APPerHealthThreshold: 3 · Mountain_AS: 0 · Mountain_DR: 0 · Mountain_DamageAmpPercent: 1% · Mountain_Health: 45% · Mountain_HexesToReveal_TOOLTIPONLY: 2 · Mountain_Resists: 12 · Mountain_StatIncrease: 0 · NumMarks: 7 · Serpent_DR: 25% · Serpent_Poison: 60% · Shield_ADAP: 4% · Shield_Shield: 35% · Wolf_ADAP: 25 · Wolf_CriticalStrikeChance: 45% · Wolf_Gold: 4 · Wolf_Health: 15% · Wolf_ModifiedCriticalStrikeDamage: 1.75"
      },
      {
        "count": 8,
        "effect": "Mountain_ADAP: 0 · Mountain_AS: 0 · Mountain_DR: 0 · Mountain_Resists: 0 · Mountain_StatIncrease: 0 · NumMarks: 3 · Shield_CashoutAS: 18 · Shield_CashoutHP: 20 · Wolf_ADAP: 10 · Wolf_Gold: 1 · Wolf_Health: 2%"
      },
      {
        "count": 9,
        "effect": "Mountain_ADAP: 12% · Mountain_AS: 12% · Mountain_DR: 6% · Mountain_Health: 12% · Mountain_Resists: 12 · Mountain_StatIncrease: 0"
      },
      {
        "count": 10,
        "effect": "Mountain_ADAP: 12% · Mountain_AS: 12% · Mountain_DR: 6% · Mountain_Health: 12% · Mountain_Resists: 12 · Mountain_StatIncrease: 10%"
      }
    ],
    "bestUnits": [
      "Jax",
      "Lulu",
      "Nunu",
      "Talon",
      "Twisted Fate",
      "Xayah"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_timebreaker",
    "name": "Timebreaker",
    "description": "Allies gain Attack Speed.\n\n AND When you lose, gain free rerolls. When you win, store XP in a Temporal Core (scales with stage).\n\n AND Timebreakers gain an additional Attack Speed\n\nRerolls on Loss: @TFTUnitProperty.:TFT17_Timebreaker_NumRerollsTooltip@\nXP on Win: @TFTUnitProperty.:TFT17_Timebreaker_NumXPTooltip@",
    "thresholds": [
      {
        "count": 2,
        "effect": "AttackSpeed: 15% · RerollXPMultiplier: 0 · TimebreakerAdditionalAS: 0"
      },
      {
        "count": 3,
        "effect": "AttackSpeed: 15% · RerollXPMultiplier: 1 · TimebreakerAdditionalAS: 0"
      },
      {
        "count": 4,
        "effect": "AttackSpeed: 15% · RerollXPMultiplier: 1 · TimebreakerAdditionalAS: 50%"
      }
    ],
    "bestUnits": [
      "Ezreal",
      "Milio",
      "Pantheon",
      "Riven"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_vanguard",
    "name": "Vanguard",
    "description": "Vanguards gain Durability while Shielded. \n\nCombat start and Health: Gain a max Health Shield for seconds. max Health max Health max Health; while Shielded",
    "thresholds": [
      {
        "count": 2,
        "effect": "EnhancedDurability: 8% · ShieldPercentAmount: 16%"
      },
      {
        "count": 4,
        "effect": "EnhancedDurability: 8% · ShieldPercentAmount: 30%"
      },
      {
        "count": 6,
        "effect": "EnhancedDurability: 8% · ShieldPercentAmount: 40%"
      }
    ],
    "bestUnits": [
      "Blitzcrank",
      "Illaoi",
      "Leona",
      "Mordekaiser",
      "Nasus",
      "Nunu"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  },
  {
    "id": "syn_voyager",
    "name": "Voyager",
    "description": "Combat Start: Your Tanks gain a Shield for seconds. Your other allies gain Damage Amp. \n\nVoyagers gain double.",
    "thresholds": [
      {
        "count": 2,
        "effect": "BonusDA: 9% · ShieldDuration: 15 · ShieldHP: 175"
      },
      {
        "count": 3,
        "effect": "BonusDA: 15% · ShieldDuration: 15 · ShieldHP: 250"
      },
      {
        "count": 4,
        "effect": "BonusDA: 18% · ShieldDuration: 15 · ShieldHP: 350"
      },
      {
        "count": 5,
        "effect": "BonusDA: 22% · ShieldDuration: 15 · ShieldHP: 500"
      },
      {
        "count": 6,
        "effect": "BonusDA: 27% · ShieldDuration: 15 · ShieldHP: 700"
      }
    ],
    "bestUnits": [
      "Aurora",
      "Karma",
      "Meepsie",
      "Pyke",
      "The Mighty Mech"
    ],
    "bestComps": [],
    "counters": [],
    "type": "hybrid"
  }
]

export function traitsForUnit(name: string, fallback: string[]): string[] {
  const t = TFT17_UNIT_TRAITS[name]
  return t?.length ? t : fallback
}
